export const mockCars = [
  {
    id: '1',
    name: 'BMW 3 Series',
    brand: 'BMW',
    model: '3 Series',
    year: 2024,
    category: 'Luxury',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    pricePerDay: 4500,
    rating: 4.8,
    reviewCount: 124,
    city: 'Delhi',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800',
    ],
    description: 'Experience luxury and performance with the BMW 3 Series. Perfect for business trips and weekend getaways.',
    features: ['GPS Navigation', 'Bluetooth', 'Leather Seats', 'Sunroof', 'Backup Camera'],
    owner: { id: 'o1', name: 'Rajesh Kumar', avatar: '', rating: 4.9 },
    location: { lat: 28.6139, lng: 77.209 },
    available: true,
  },
  {
    id: '2',
    name: 'Mercedes-Benz C-Class',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2023,
    category: 'Luxury',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 5,
    pricePerDay: 5000,
    rating: 4.9,
    reviewCount: 98,
    city: 'Mumbai',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    ],
    description: 'Drive in style with the Mercedes-Benz C-Class. Elegant design meets cutting-edge technology.',
    features: ['GPS Navigation', 'Premium Sound', 'Leather Seats', 'Panoramic Roof'],
    owner: { id: 'o2', name: 'Priya Sharma', avatar: '', rating: 4.8 },
    location: { lat: 19.076, lng: 72.8777 },
    available: true,
  },
  {
    id: '3',
    name: 'Toyota Fortuner',
    brand: 'Toyota',
    model: 'Fortuner',
    year: 2024,
    category: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 7,
    pricePerDay: 3500,
    rating: 4.7,
    reviewCount: 210,
    city: 'Bangalore',
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1519641471654-76cead7a7fe3?w=800',
    ],
    description: 'Spacious and powerful SUV perfect for family trips and off-road adventures.',
    features: ['4WD', 'GPS Navigation', '7 Seats', 'Roof Rails'],
    owner: { id: 'o3', name: 'Amit Patel', avatar: '', rating: 4.7 },
    location: { lat: 12.9716, lng: 77.5946 },
    available: true,
  },
  {
    id: '4',
    name: 'Honda City',
    brand: 'Honda',
    model: 'City',
    year: 2023,
    category: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    pricePerDay: 1800,
    rating: 4.5,
    reviewCount: 156,
    city: 'Delhi',
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    ],
    description: 'Reliable and fuel-efficient sedan ideal for city commuting.',
    features: ['GPS Navigation', 'Bluetooth', 'Cruise Control'],
    owner: { id: 'o4', name: 'Sneha Reddy', avatar: '', rating: 4.6 },
    location: { lat: 28.5355, lng: 77.391 },
    available: true,
  },
  {
    id: '5',
    name: 'Tesla Model 3',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2024,
    category: 'Luxury',
    transmission: 'Automatic',
    fuelType: 'Electric',
    seats: 5,
    pricePerDay: 6000,
    rating: 4.9,
    reviewCount: 87,
    city: 'Mumbai',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    ],
    description: 'Experience the future of driving with Tesla Model 3. Zero emissions, maximum performance.',
    features: ['Autopilot', 'Supercharging', 'Premium Interior', 'Glass Roof'],
    owner: { id: 'o5', name: 'Vikram Singh', avatar: '', rating: 5.0 },
    location: { lat: 19.0176, lng: 72.8562 },
    available: true,
  },
  {
    id: '6',
    name: 'Maruti Swift',
    brand: 'Maruti',
    model: 'Swift',
    year: 2023,
    category: 'Hatchback',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    pricePerDay: 1200,
    rating: 4.3,
    reviewCount: 320,
    city: 'Bangalore',
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',
    ],
    description: 'Compact and economical hatchback perfect for city driving.',
    features: ['Bluetooth', 'Power Windows', 'ABS'],
    owner: { id: 'o6', name: 'Kavita Nair', avatar: '', rating: 4.4 },
    location: { lat: 12.9352, lng: 77.6245 },
    available: true,
  },
];

export const mockTestimonials = [
  {
    id: '1',
    name: 'Rahul Mehta',
    avatar: '',
    rating: 5,
    comment: 'Amazing experience! The car was in perfect condition and the booking process was seamless.',
    car: 'BMW 3 Series',
  },
  {
    id: '2',
    name: 'Anita Desai',
    avatar: '',
    rating: 5,
    comment: 'Great platform for renting cars. Found exactly what I needed for my family trip.',
    car: 'Toyota Fortuner',
  },
  {
    id: '3',
    name: 'Suresh Iyer',
    avatar: '',
    rating: 4,
    comment: 'Good service and competitive prices. Will definitely use again.',
    car: 'Honda City',
  },
];

export const mockCategories = [
  { id: '1', name: 'Sedan', icon: '🚗', count: 45 },
  { id: '2', name: 'SUV', icon: '🚙', count: 32 },
  { id: '3', name: 'Hatchback', icon: '🚘', count: 28 },
  { id: '4', name: 'Luxury', icon: '✨', count: 18 },
  { id: '5', name: 'Sports', icon: '🏎️', count: 12 },
  { id: '6', name: 'Van', icon: '🚐', count: 8 },
];

export const mockNotifications = [
  {
    id: '1',
    type: 'booking',
    title: 'Booking Confirmed',
    message: 'Your booking for BMW 3 Series has been confirmed.',
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    type: 'payment',
    title: 'Payment Successful',
    message: 'Payment of ₹13,500 received for booking #1234.',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '3',
    type: 'review',
    title: 'New Review',
    message: 'You received a 5-star review for your Toyota Fortuner.',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const mockConversations = [
  {
    id: '1',
    participant: { id: 'o1', name: 'Rajesh Kumar', avatar: '', online: true },
    lastMessage: 'The car is ready for pickup!',
    lastMessageAt: new Date().toISOString(),
    unreadCount: 1,
  },
  {
    id: '2',
    participant: { id: 'o2', name: 'Priya Sharma', avatar: '', online: false },
    lastMessage: 'Thank you for renting!',
    lastMessageAt: new Date(Date.now() - 7200000).toISOString(),
    unreadCount: 0,
  },
];

export const mockMessages = [
  {
    id: '1',
    senderId: 'o1',
    content: 'Hello! Your booking is confirmed.',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    read: true,
  },
  {
    id: '2',
    senderId: 'user',
    content: 'Great! What time can I pick up the car?',
    createdAt: new Date(Date.now() - 3000000).toISOString(),
    read: true,
  },
  {
    id: '3',
    senderId: 'o1',
    content: 'The car is ready for pickup!',
    createdAt: new Date().toISOString(),
    read: false,
  },
];

export const mockAdminStats = {
  totalUsers: 1250,
  totalCars: 340,
  totalBookings: 2890,
  totalRevenue: 4560000,
  recentBookings: 45,
  activeUsers: 890,
};
